// Monetization settings. Mirrors the tab structure in docs/admin-portal-spec.md §4.
//
// Secrets (`secret: true`) are never returned in admin reads and are expected to
// come from environment variables; the declaration exists so the admin UI can
// show whether they are configured.

const SECTIONS = {
  GENERAL: 'monetization.general',
  PRICING: 'monetization.pricing',
  ACCESS: 'monetization.access',
  EXPIRY: 'monetization.expiry',
  STORE: 'monetization.store',
  CURRENCY: 'monetization.currency',
  PAYPAL: 'monetization.paypal',
  SUBSCRIPTIONS: 'monetization.subscriptions',
  COUPONS: 'monetization.coupons',
  GRANTS: 'monetization.grants',
  REFUNDS: 'monetization.refunds',
  TAX: 'monetization.tax',
  REVENUE_SHARE: 'monetization.revenueShare',
  GEO: 'monetization.geo',
  ANALYTICS: 'monetization.analytics',
  SAFETY: 'monetization.safety',
  RATE_LIMITS: 'monetization.rateLimits',
};

const settings = [
  // ---------------------------------------------------------------- general
  {
    key: 'monetization.enabled',
    section: SECTIONS.GENERAL,
    type: 'boolean',
    default: false,
    label: 'Enable monetization',
    help: 'Master switch. When off every chapter is free and the store is hidden.',
    requiresConfirmation: true,
    impact: 'monetizationKillSwitch',
    public: true,
  },
  {
    key: 'monetization.readOnlyMode',
    section: SECTIONS.GENERAL,
    type: 'boolean',
    default: false,
    label: 'Read-only mode',
    help: 'The store stays browsable but no new orders can be created.',
    public: true,
  },
  {
    key: 'credits.labelSingular',
    section: SECTIONS.GENERAL,
    type: 'string',
    default: 'Credit',
    maxLength: 24,
    label: 'Credit name (singular)',
    public: true,
  },
  {
    key: 'credits.labelPlural',
    section: SECTIONS.GENERAL,
    type: 'string',
    default: 'Credits',
    maxLength: 24,
    label: 'Credit name (plural)',
    public: true,
  },
  {
    key: 'credits.perUsd',
    section: SECTIONS.GENERAL,
    type: 'integer',
    default: 100,
    min: 1,
    max: 1000000,
    label: 'Credits per USD',
    help: 'The core conversion rate. Pack prices are stored in USD and are not affected, but every outstanding balance changes in content value.',
    requiresConfirmation: true,
    impact: 'revalueBalances',
    public: true,
  },
  {
    key: 'credits.showCalculator',
    section: SECTIONS.GENERAL,
    type: 'boolean',
    default: true,
    label: 'Show the credit calculator',
    public: true,
  },
  {
    key: 'credits.minPurchaseUsdCents',
    section: SECTIONS.GENERAL,
    type: 'money_usd_cents',
    default: 100,
    max: 100000,
    label: 'Minimum purchase',
  },
  {
    key: 'credits.maxPurchaseUsdCents',
    section: SECTIONS.GENERAL,
    type: 'money_usd_cents',
    default: 50000,
    max: 10000000,
    label: 'Maximum purchase',
  },
  {
    key: 'credits.allowNegativeBalance',
    section: SECTIONS.GENERAL,
    type: 'boolean',
    default: false,
    label: 'Allow negative balances',
    help: 'Only reachable through a refund clawback after credits were already spent.',
  },
  {
    key: 'credits.roundingMode',
    section: SECTIONS.GENERAL,
    type: 'enum',
    default: 'round',
    options: [
      { value: 'floor', label: 'Round down' },
      { value: 'round', label: 'Round to nearest' },
      { value: 'ceil', label: 'Round up' },
    ],
    label: 'Rounding for computed grants',
  },
  {
    key: 'credits.lowBalanceThreshold',
    section: SECTIONS.GENERAL,
    type: 'integer',
    default: 20,
    min: 0,
    max: 100000,
    label: 'Low balance threshold',
    help: '0 disables the low-balance nudge.',
    // The reader UI highlights a low balance in the navbar, so it needs the
    // configured value — without this it silently used the built-in default.
    public: true,
  },
  {
    key: 'credits.showLifetimeStats',
    section: SECTIONS.GENERAL,
    type: 'boolean',
    default: true,
    label: 'Show lifetime stats on the profile',
    public: true,
  },

  // ---------------------------------------------------------------- pricing
  {
    key: 'pricing.defaultChapterCredits',
    section: SECTIONS.PRICING,
    type: 'integer',
    default: 10,
    min: 0,
    max: 100000,
    label: 'Default chapter price',
    unit: 'credits',
    requiresConfirmation: true,
    impact: 'repriceChapters',
  },
  {
    key: 'pricing.defaultFreeChapterCount',
    section: SECTIONS.PRICING,
    type: 'integer',
    default: 10,
    min: 0,
    max: 100000,
    label: 'Free chapters per novel',
    help: 'The first N chapters are always free unless a novel overrides this.',
    requiresConfirmation: true,
    impact: 'repriceChapters',
  },
  {
    key: 'pricing.defaultFreeAfterDays',
    section: SECTIONS.PRICING,
    type: 'integer',
    default: 0,
    min: 0,
    max: 3650,
    label: 'Chapters become free after',
    unit: 'days',
    help: '0 means paid chapters never become free automatically.',
  },
  {
    key: 'pricing.previewParagraphs',
    section: SECTIONS.PRICING,
    type: 'integer',
    default: 3,
    min: 0,
    max: 50,
    label: 'Free preview before the paywall',
    unit: 'paragraphs',
    public: true,
  },
  {
    key: 'pricing.gateStacking',
    section: SECTIONS.PRICING,
    type: 'enum',
    default: 'both',
    options: [
      { value: 'both', label: 'Require engagement and credits' },
      { value: 'credits_bypass_engagement', label: 'Paying skips the engagement gate' },
      { value: 'engagement_bypass_credits', label: 'Engagement skips the paywall' },
    ],
    label: 'When both gates apply',
  },
  {
    key: 'pricing.allowBulkUnlock',
    section: SECTIONS.PRICING,
    type: 'boolean',
    default: true,
    label: 'Allow bulk unlock',
    public: true,
  },
  {
    key: 'pricing.bulkDiscountTiers',
    section: SECTIONS.PRICING,
    type: 'json',
    default: [
      { minChapters: 5, discountPct: 5 },
      { minChapters: 10, discountPct: 10 },
      { minChapters: 25, discountPct: 15 },
    ],
    arrayOf: true,
    itemShape: ['minChapters', 'discountPct'],
    label: 'Bulk discount tiers',
    public: true,
  },
  {
    key: 'pricing.allowAutoUnlock',
    section: SECTIONS.PRICING,
    type: 'boolean',
    // Defaults off because the engine that would act on the preference is not
    // built yet. On, readers get a toggle that saves happily and then never
    // unlocks anything — a control that lies is worse than one that is absent.
    default: false,
    label: 'Allow auto-unlock',
    help:
      'NOT YET ACTIVE. The reader preference is stored but nothing spends credits automatically, ' +
      'so turning this on only shows readers a toggle that does nothing. Leave off until the ' +
      'auto-unlock engine ships.',
    public: true,
  },
  {
    key: 'pricing.autoUnlockMaxCredits',
    section: SECTIONS.PRICING,
    type: 'integer',
    default: 25,
    min: 0,
    max: 100000,
    label: 'Auto-unlock price ceiling',
    unit: 'credits',
    public: true,
  },
  {
    key: 'pricing.roundToNearestCredits',
    section: SECTIONS.PRICING,
    type: 'integer',
    default: 1,
    min: 1,
    max: 1000,
    label: 'Round chapter prices to',
    unit: 'credits',
  },
  {
    key: 'pricing.showPricesOnChapterList',
    section: SECTIONS.PRICING,
    type: 'boolean',
    default: true,
    label: 'Show prices on the chapter list',
    public: true,
  },

  // ----------------------------------------------------------------- access
  {
    key: 'access.mode',
    section: SECTIONS.ACCESS,
    type: 'enum',
    default: 'permanent',
    options: [
      { value: 'permanent', label: 'Unlocks are permanent' },
      { value: 'rental', label: 'Unlocks expire' },
      { value: 'hybrid', label: 'Reader chooses' },
    ],
    label: 'Access model',
    requiresConfirmation: true,
  },
  {
    key: 'access.rentalHours',
    section: SECTIONS.ACCESS,
    type: 'integer',
    default: 72,
    min: 1,
    max: 8760,
    label: 'Rental duration',
    unit: 'hours',
    dependsOn: { key: 'access.mode', notEquals: 'permanent' },
  },
  {
    key: 'access.rentalPriceMultiplier',
    section: SECTIONS.ACCESS,
    type: 'number',
    default: 0.5,
    min: 0.01,
    max: 1,
    label: 'Rental price multiplier',
    dependsOn: { key: 'access.mode', notEquals: 'permanent' },
  },
  {
    key: 'access.allowRentalUpgrade',
    section: SECTIONS.ACCESS,
    type: 'boolean',
    default: true,
    label: 'Allow upgrading a rental to permanent',
    dependsOn: { key: 'access.mode', notEquals: 'permanent' },
  },
  {
    key: 'access.rentalUpgradeCreditsRental',
    section: SECTIONS.ACCESS,
    type: 'boolean',
    default: true,
    label: 'Credit the rental price toward the upgrade',
    dependsOn: { key: 'access.mode', notEquals: 'permanent' },
  },
  {
    key: 'access.rentalExpiryWarningHours',
    section: SECTIONS.ACCESS,
    type: 'integer',
    default: 12,
    min: 0,
    max: 168,
    label: 'Warn before a rental expires',
    unit: 'hours',
    dependsOn: { key: 'access.mode', notEquals: 'permanent' },
  },

  // ----------------------------------------------------------------- expiry
  {
    key: 'expiry.enabled',
    section: SECTIONS.EXPIRY,
    type: 'boolean',
    default: false,
    label: 'Enable credit expiry',
    help: 'Credit tranches always exist for revenue attribution. This only controls whether they expire.',
    requiresConfirmation: true,
  },
  {
    key: 'expiry.defaultDays',
    section: SECTIONS.EXPIRY,
    type: 'integer',
    default: 0,
    min: 0,
    max: 3650,
    label: 'Default expiry',
    unit: 'days',
    help: '0 means never.',
    dependsOn: { key: 'expiry.enabled', equals: true },
  },
  {
    key: 'expiry.bySource',
    section: SECTIONS.EXPIRY,
    type: 'json',
    default: { purchase: 0, grant: 90, subscription: 30, referral: 90 },
    label: 'Expiry by credit source',
    unit: 'days',
    dependsOn: { key: 'expiry.enabled', equals: true },
  },
  {
    key: 'expiry.consumptionOrder',
    section: SECTIONS.EXPIRY,
    type: 'enum',
    default: 'expiry_first',
    options: [
      { value: 'expiry_first', label: 'Soonest to expire first' },
      { value: 'fifo', label: 'Oldest first' },
      { value: 'granted_first', label: 'Granted credits first' },
      { value: 'purchased_first', label: 'Purchased credits first' },
    ],
    label: 'Spend order',
    help: 'Also determines which cost basis a chapter unlock draws from.',
  },
  {
    key: 'expiry.warnDaysBefore',
    section: SECTIONS.EXPIRY,
    type: 'integer',
    default: 7,
    min: 0,
    max: 365,
    label: 'Warn before expiry',
    unit: 'days',
    dependsOn: { key: 'expiry.enabled', equals: true },
  },
  {
    key: 'expiry.sweepCron',
    section: SECTIONS.EXPIRY,
    type: 'cron',
    default: '0 3 * * *',
    label: 'Expiry sweep schedule',
    dependsOn: { key: 'expiry.enabled', equals: true },
  },

  // ------------------------------------------------------------------ store
  {
    key: 'store.enabled',
    section: SECTIONS.STORE,
    type: 'boolean',
    default: false,
    label: 'Store enabled',
    public: true,
  },
  {
    key: 'store.heading',
    section: SECTIONS.STORE,
    type: 'string',
    default: 'Get credits',
    maxLength: 120,
    label: 'Store heading',
    public: true,
  },
  {
    key: 'store.subheading',
    section: SECTIONS.STORE,
    type: 'text',
    default: 'Unlock chapters and support the authors you read.',
    maxLength: 400,
    label: 'Store subheading',
    public: true,
  },
  {
    key: 'store.layout',
    section: SECTIONS.STORE,
    type: 'enum',
    default: 'grid',
    options: [
      { value: 'grid', label: 'Grid' },
      { value: 'list', label: 'List' },
      { value: 'carousel', label: 'Carousel' },
    ],
    label: 'Pack layout',
    public: true,
  },
  {
    key: 'store.requireTermsAcceptance',
    section: SECTIONS.STORE,
    type: 'boolean',
    default: true,
    label: 'Require accepting terms at checkout',
    public: true,
  },
  {
    key: 'store.orderQuoteTtlMinutes',
    section: SECTIONS.STORE,
    type: 'integer',
    default: 15,
    min: 1,
    max: 1440,
    label: 'Price lock duration',
    unit: 'minutes',
  },

  // --------------------------------------------------------------- currency
  {
    key: 'currency.default',
    section: SECTIONS.CURRENCY,
    type: 'string',
    default: 'USD',
    maxLength: 3,
    pattern: '^[A-Z]{3}$',
    patternHint: 'must be a 3-letter ISO-4217 code',
    label: 'Default currency',
    public: true,
  },
  {
    key: 'currency.autoDetect',
    section: SECTIONS.CURRENCY,
    type: 'boolean',
    default: true,
    label: 'Detect currency from location',
    public: true,
  },
  {
    key: 'currency.allowUserOverride',
    section: SECTIONS.CURRENCY,
    type: 'boolean',
    default: true,
    label: 'Let readers pick their currency',
    public: true,
  },
  {
    key: 'currency.lockAfterFirstPurchase',
    section: SECTIONS.CURRENCY,
    type: 'boolean',
    default: false,
    label: 'Lock currency after the first purchase',
  },
  {
    key: 'currency.globalMarkupPct',
    section: SECTIONS.CURRENCY,
    type: 'number',
    default: 2,
    min: 0,
    max: 50,
    label: 'FX markup',
    unit: '%',
    help: 'Buffer against rate movement between quote and settlement.',
  },
  {
    key: 'fx.providerUrl',
    section: SECTIONS.CURRENCY,
    type: 'string',
    default: 'https://open.er-api.com/v6/latest/USD',
    maxLength: 500,
    label: 'Exchange rate provider',
  },
  {
    key: 'fx.refreshCron',
    section: SECTIONS.CURRENCY,
    type: 'cron',
    default: '0 */6 * * *',
    label: 'Rate refresh schedule',
  },
  {
    key: 'fx.staleAfterHours',
    section: SECTIONS.CURRENCY,
    type: 'integer',
    default: 48,
    min: 1,
    max: 720,
    label: 'Rates go stale after',
    unit: 'hours',
  },
  {
    key: 'fx.onStaleRates',
    section: SECTIONS.CURRENCY,
    type: 'enum',
    default: 'fallback_usd',
    options: [
      { value: 'fallback_usd', label: 'Charge in USD instead' },
      { value: 'use_last_known', label: 'Use the last known rate' },
      { value: 'block_purchases', label: 'Block purchases' },
    ],
    label: 'When rates are stale',
  },

  // ----------------------------------------------------------------- paypal
  {
    key: 'paypal.environment',
    section: SECTIONS.PAYPAL,
    type: 'enum',
    default: 'sandbox',
    options: [
      { value: 'sandbox', label: 'Sandbox' },
      { value: 'live', label: 'Live' },
    ],
    label: 'PayPal environment',
    requiresConfirmation: true,
  },
  {
    key: 'paypal.clientId',
    section: SECTIONS.PAYPAL,
    type: 'string',
    default: '',
    maxLength: 200,
    label: 'Client ID',
    envVar: 'PAYPAL_CLIENT_ID',
  },
  {
    key: 'paypal.clientSecret',
    section: SECTIONS.PAYPAL,
    type: 'string',
    default: '',
    maxLength: 200,
    label: 'Client secret',
    secret: true,
    envVar: 'PAYPAL_CLIENT_SECRET',
  },
  {
    key: 'paypal.webhookId',
    section: SECTIONS.PAYPAL,
    type: 'string',
    default: '',
    maxLength: 200,
    label: 'Webhook ID',
    secret: true,
    envVar: 'PAYPAL_WEBHOOK_ID',
  },
  {
    key: 'paypal.brandName',
    section: SECTIONS.PAYPAL,
    type: 'string',
    default: 'Apex NovelHub',
    maxLength: 127,
    label: 'Brand name shown at checkout',
    public: true,
  },
  {
    key: 'paypal.enabledFundingSources',
    section: SECTIONS.PAYPAL,
    type: 'multiselect',
    default: ['paypal', 'card'],
    options: [
      { value: 'paypal', label: 'PayPal balance' },
      { value: 'card', label: 'Debit or credit card' },
      { value: 'venmo', label: 'Venmo' },
      { value: 'paylater', label: 'Pay Later' },
    ],
    label: 'Funding sources',
    public: true,
  },

  // ---------------------------------------------------------- subscriptions
  {
    key: 'subscriptions.enabled',
    section: SECTIONS.SUBSCRIPTIONS,
    type: 'boolean',
    default: false,
    label: 'Enable subscriptions',
    help: 'Recurring plans that grant credits each cycle and can unlock chapters directly.',
    public: true,
  },
  {
    key: 'subscriptions.gracePeriodDays',
    section: SECTIONS.SUBSCRIPTIONS,
    type: 'integer',
    default: 3,
    min: 0,
    max: 30,
    label: 'Grace period after a failed payment',
    unit: 'days',
    help: 'Perks continue during this window while PayPal retries.',
  },
  {
    key: 'subscriptions.allowPlanChange',
    section: SECTIONS.SUBSCRIPTIONS,
    type: 'boolean',
    default: true,
    label: 'Let subscribers change plan',
    public: true,
  },
  {
    key: 'subscriptions.cancelAtPeriodEnd',
    section: SECTIONS.SUBSCRIPTIONS,
    type: 'boolean',
    default: true,
    label: 'Cancellation takes effect at period end',
    help: 'Off means access stops immediately, which usually reads as punitive.',
    public: true,
  },
  {
    key: 'subscriptions.creditsExpireWithCycle',
    section: SECTIONS.SUBSCRIPTIONS,
    type: 'boolean',
    default: false,
    label: 'Cycle credits expire when the next cycle starts',
    help: 'Use-it-or-lose-it. Off lets unspent cycle credits accumulate.',
  },
  {
    key: 'subscriptions.cancellationCopy',
    section: SECTIONS.SUBSCRIPTIONS,
    type: 'text',
    default: '',
    maxLength: 1000,
    label: 'Message shown when cancelling',
    public: true,
  },
  {
    key: 'subscriptions.showBadge',
    section: SECTIONS.SUBSCRIPTIONS,
    type: 'boolean',
    default: true,
    label: 'Show the subscriber badge on profiles and comments',
    public: true,
  },
  {
    key: 'subscriptions.storeHeading',
    section: SECTIONS.SUBSCRIPTIONS,
    type: 'string',
    default: 'Read more, pay less',
    maxLength: 120,
    label: 'Plan picker heading',
    public: true,
  },
  {
    key: 'subscriptions.expireCron',
    section: SECTIONS.SUBSCRIPTIONS,
    type: 'cron',
    default: '15 * * * *',
    label: 'Lapsed subscription sweep',
    help: 'When suspended and ended subscriptions are closed out and their cycle revenue attributed.',
    advanced: true,
  },

  // ---------------------------------------------------------------- coupons
  {
    key: 'coupons.enabled',
    section: SECTIONS.COUPONS,
    type: 'boolean',
    default: false,
    label: 'Enable coupon codes',
    public: true,
  },
  {
    key: 'coupons.allowStacking',
    section: SECTIONS.COUPONS,
    type: 'boolean',
    default: false,
    label: 'Allow more than one code per order',
  },
  {
    key: 'coupons.codeLength',
    section: SECTIONS.COUPONS,
    type: 'integer',
    default: 10,
    min: 6,
    max: 32,
    label: 'Generated code length',
    help: 'Shorter codes are easier to share and easier to brute-force.',
  },
  {
    key: 'coupons.showFieldAtCheckout',
    section: SECTIONS.COUPONS,
    type: 'boolean',
    default: true,
    label: 'Show a coupon field at checkout',
    public: true,
  },

  // ---------------------------------------------------------------- refunds
  {
    key: 'refunds.selfServiceEnabled',
    section: SECTIONS.REFUNDS,
    type: 'boolean',
    default: false,
    label: 'Allow self-service refunds',
    public: true,
  },
  {
    key: 'refunds.windowHours',
    section: SECTIONS.REFUNDS,
    type: 'integer',
    default: 48,
    min: 1,
    max: 8760,
    label: 'Refund window',
    unit: 'hours',
    public: true,
  },
  {
    key: 'refunds.maxPerUserPerYear',
    section: SECTIONS.REFUNDS,
    type: 'integer',
    default: 2,
    min: 0,
    max: 100,
    label: 'Refunds allowed per user per year',
  },
  {
    key: 'refunds.requireCreditsUnspent',
    section: SECTIONS.REFUNDS,
    type: 'boolean',
    default: true,
    label: 'Only refund unspent credits',
  },
  {
    key: 'refunds.onSpentCredits',
    section: SECTIONS.REFUNDS,
    type: 'enum',
    default: 'refuse',
    options: [
      { value: 'refuse', label: 'Refuse the refund' },
      { value: 'allow_negative', label: 'Refund and allow a negative balance' },
      { value: 'revoke_access', label: 'Refund and revoke unlocked chapters' },
      { value: 'prorate', label: 'Refund only the unspent portion' },
    ],
    label: 'If credits were already spent',
    requiresConfirmation: true,
  },
  {
    key: 'refunds.autoApproveUnderUsdCents',
    section: SECTIONS.REFUNDS,
    type: 'money_usd_cents',
    default: 500,
    max: 100000,
    label: 'Auto-approve refunds under',
  },
  {
    key: 'refunds.blockPurchasesAfterCount',
    section: SECTIONS.REFUNDS,
    type: 'integer',
    default: 3,
    min: 0,
    max: 100,
    label: 'Block purchases after this many refunds',
  },
  {
    key: 'refunds.accidentalUnlockEnabled',
    section: SECTIONS.REFUNDS,
    type: 'boolean',
    default: true,
    label: 'Allow undoing an accidental unlock',
    public: true,
  },
  {
    key: 'refunds.accidentalUnlockWindowMinutes',
    section: SECTIONS.REFUNDS,
    type: 'integer',
    default: 5,
    min: 1,
    max: 1440,
    label: 'Undo window',
    unit: 'minutes',
    public: true,
  },
  {
    key: 'refunds.accidentalUnlockMaxPerMonth',
    section: SECTIONS.REFUNDS,
    type: 'integer',
    default: 3,
    min: 0,
    max: 100,
    label: 'Undos allowed per month',
  },

  // -------------------------------------------------------------------- tax
  {
    key: 'tax.enabled',
    section: SECTIONS.TAX,
    type: 'boolean',
    default: false,
    label: 'Collect tax',
    help: 'Selling digital goods into the EU, India and many US states creates tax obligations that PayPal does not handle for you.',
    requiresConfirmation: true,
  },
  {
    key: 'tax.pricesIncludeTax',
    section: SECTIONS.TAX,
    type: 'boolean',
    default: false,
    label: 'Displayed prices include tax',
    public: true,
    dependsOn: { key: 'tax.enabled', equals: true },
  },
  {
    key: 'tax.defaultRatePct',
    section: SECTIONS.TAX,
    type: 'number',
    default: 0,
    min: 0,
    max: 100,
    label: 'Fallback tax rate',
    unit: '%',
    dependsOn: { key: 'tax.enabled', equals: true },
  },
  {
    key: 'tax.collectCustomerTaxId',
    section: SECTIONS.TAX,
    type: 'boolean',
    default: false,
    label: 'Collect a customer tax ID',
    dependsOn: { key: 'tax.enabled', equals: true },
  },
  {
    key: 'tax.invoicePrefix',
    section: SECTIONS.TAX,
    type: 'string',
    default: 'NH',
    maxLength: 10,
    label: 'Invoice number prefix',
  },
  {
    key: 'tax.merchantLegalName',
    section: SECTIONS.TAX,
    type: 'string',
    default: '',
    maxLength: 200,
    label: 'Legal entity name on receipts',
  },
  {
    key: 'tax.refundPolicyText',
    section: SECTIONS.TAX,
    type: 'text',
    default: '',
    maxLength: 5000,
    label: 'Refund policy',
    public: true,
  },

  // --------------------------------------------------------- revenue share
  {
    key: 'revenueShare.enabled',
    section: SECTIONS.REVENUE_SHARE,
    type: 'boolean',
    default: false,
    label: 'Enable author revenue share',
  },
  {
    key: 'revenueShare.defaultPct',
    section: SECTIONS.REVENUE_SHARE,
    type: 'number',
    default: 50,
    min: 0,
    max: 100,
    label: 'Default author share',
    unit: '%',
    dependsOn: { key: 'revenueShare.enabled', equals: true },
  },
  {
    key: 'revenueShare.basis',
    section: SECTIONS.REVENUE_SHARE,
    type: 'enum',
    default: 'net_after_fees',
    options: [
      { value: 'gross', label: 'Gross revenue' },
      { value: 'net_after_fees', label: 'After payment fees' },
      { value: 'net_after_fees_and_tax', label: 'After fees and tax' },
    ],
    label: 'Share calculated on',
    dependsOn: { key: 'revenueShare.enabled', equals: true },
  },
  {
    key: 'revenueShare.includeGrantFunded',
    section: SECTIONS.REVENUE_SHARE,
    type: 'boolean',
    default: false,
    label: 'Include unlocks paid with free credits',
    help: 'Those unlocks generated no cash, so including them pays authors from your margin.',
    dependsOn: { key: 'revenueShare.enabled', equals: true },
  },
  {
    key: 'revenueShare.minPayoutUsdCents',
    section: SECTIONS.REVENUE_SHARE,
    type: 'money_usd_cents',
    default: 5000,
    max: 1000000,
    label: 'Minimum payout',
    dependsOn: { key: 'revenueShare.enabled', equals: true },
  },
  {
    key: 'revenueShare.holdbackDays',
    section: SECTIONS.REVENUE_SHARE,
    type: 'integer',
    default: 30,
    min: 0,
    max: 365,
    label: 'Chargeback holdback',
    unit: 'days',
    dependsOn: { key: 'revenueShare.enabled', equals: true },
  },

  // -------------------------------------------------------------------- geo
  {
    key: 'geo.enabled',
    section: SECTIONS.GEO,
    type: 'boolean',
    default: true,
    label: 'Detect reader country',
  },
  {
    key: 'geo.source',
    section: SECTIONS.GEO,
    type: 'enum',
    default: 'cf_header',
    options: [
      { value: 'cf_header', label: 'Cloudflare CF-IPCountry header' },
      { value: 'custom_header', label: 'Custom header' },
      { value: 'geoip', label: 'GeoIP lookup' },
      { value: 'off', label: 'Do not detect' },
    ],
    label: 'Detection source',
    dependsOn: { key: 'geo.enabled', equals: true },
  },
  {
    key: 'geo.customHeaderName',
    section: SECTIONS.GEO,
    type: 'string',
    default: '',
    maxLength: 80,
    label: 'Custom header name',
    dependsOn: { key: 'geo.source', equals: 'custom_header' },
  },
  {
    key: 'geo.fallbackCountry',
    section: SECTIONS.GEO,
    type: 'string',
    default: 'US',
    maxLength: 2,
    pattern: '^[A-Z]{2}$',
    patternHint: 'must be a 2-letter ISO country code',
    label: 'Fallback country',
  },
  {
    key: 'geo.restrictedCountries',
    section: SECTIONS.GEO,
    type: 'multiselect',
    default: [],
    maxItems: 300,
    label: 'Countries blocked from purchasing',
  },
  {
    key: 'geo.regionPricingEnabled',
    section: SECTIONS.GEO,
    type: 'boolean',
    default: false,
    label: 'Purchasing-power pricing',
    help: 'Applies a per-region multiplier on top of the FX conversion.',
  },
  {
    key: 'geo.regionMultipliers',
    section: SECTIONS.GEO,
    type: 'json',
    default: [],
    arrayOf: true,
    itemShape: ['countries', 'multiplier'],
    label: 'Region multipliers',
    dependsOn: { key: 'geo.regionPricingEnabled', equals: true },
  },

  // -------------------------------------------------------------- analytics
  {
    key: 'analytics.revenueBasis',
    section: SECTIONS.ANALYTICS,
    type: 'enum',
    default: 'attributed_cash',
    options: [
      { value: 'attributed_cash', label: 'Attributed cash' },
      { value: 'face_value', label: 'Credit face value' },
      { value: 'both', label: 'Show both' },
    ],
    label: 'Primary revenue metric',
    help: 'Attributed cash traces each unlock to the money that actually bought those credits.',
  },
  {
    key: 'analytics.subscriptionAttribution',
    section: SECTIONS.ANALYTICS,
    type: 'enum',
    default: 'per_chapter_prorata',
    options: [
      { value: 'none', label: 'Do not attribute to chapters' },
      { value: 'per_chapter_prorata', label: 'Split across chapters read' },
      { value: 'per_novel_prorata', label: 'Split across novels read' },
    ],
    label: 'Subscription revenue attribution',
  },
  {
    key: 'analytics.deductPaymentFees',
    section: SECTIONS.ANALYTICS,
    type: 'boolean',
    default: true,
    label: 'Report revenue net of payment fees',
  },
  {
    key: 'analytics.includeTaxInRevenue',
    section: SECTIONS.ANALYTICS,
    type: 'boolean',
    default: false,
    label: 'Include collected tax in revenue',
    help: 'Tax collected on your behalf is not revenue. Leave off unless you know otherwise.',
  },
  {
    key: 'analytics.rollupCron',
    section: SECTIONS.ANALYTICS,
    type: 'cron',
    default: '0 * * * *',
    label: 'Rollup schedule',
  },
  {
    key: 'analytics.defaultRangeDays',
    section: SECTIONS.ANALYTICS,
    type: 'integer',
    default: 30,
    min: 1,
    max: 365,
    label: 'Default dashboard range',
    unit: 'days',
  },

  // ----------------------------------------------------------------- safety
  {
    key: 'safety.blockDeleteOfPurchasedChapters',
    section: SECTIONS.SAFETY,
    type: 'boolean',
    default: true,
    label: 'Protect purchased chapters from deletion',
  },
  {
    key: 'safety.onChapterDelete',
    section: SECTIONS.SAFETY,
    type: 'enum',
    default: 'block',
    options: [
      { value: 'block', label: 'Refuse the delete' },
      { value: 'refund_credits', label: 'Refund everyone who paid' },
      { value: 'refund_and_notify', label: 'Refund and notify' },
    ],
    label: 'Deleting a purchased chapter',
  },
  {
    key: 'safety.onTransactedUserDelete',
    section: SECTIONS.SAFETY,
    type: 'enum',
    default: 'anonymize',
    options: [
      { value: 'block', label: 'Refuse the delete' },
      { value: 'anonymize', label: 'Anonymize but keep financial records' },
      { value: 'full_delete', label: 'Delete everything' },
    ],
    label: 'Deleting a user who has transacted',
    help: 'Tax records normally must be retained, so anonymizing is usually the correct choice.',
  },
  {
    key: 'safety.freezeFreeCountByOriginalNumber',
    section: SECTIONS.SAFETY,
    type: 'boolean',
    default: true,
    label: 'Free-chapter count follows original numbering',
    help: 'Stops renumbering from silently moving paid chapters into the free range.',
  },
  {
    key: 'safety.importDefaultAccessType',
    section: SECTIONS.SAFETY,
    type: 'enum',
    default: 'inherit',
    options: [
      { value: 'inherit', label: 'Inherit from the novel' },
      { value: 'free', label: 'Free' },
      { value: 'paid', label: 'Paid' },
    ],
    label: 'Access type for bulk-imported chapters',
  },
  {
    key: 'safety.requireImportPricingConfirmation',
    section: SECTIONS.SAFETY,
    type: 'boolean',
    default: true,
    label: 'Confirm pricing before a bulk import',
    help: 'Importing 200 chapters into a monetized novel is a mass paywall event.',
  },
  {
    key: 'safety.maxManualAdjustmentCredits',
    section: SECTIONS.SAFETY,
    type: 'integer',
    default: 1000,
    min: 0,
    max: 10000000,
    label: 'Manual wallet adjustment cap',
    unit: 'credits',
    help: 'Adjustments above this need a second approver.',
  },

  // ------------------------------------------------------------ rate limits
  {
    key: 'rateLimits.enabled',
    section: SECTIONS.RATE_LIMITS,
    type: 'boolean',
    default: true,
    label: 'Enable rate limiting',
  },
  {
    key: 'rateLimits.orderCreatePerMinute',
    section: SECTIONS.RATE_LIMITS,
    type: 'integer',
    default: 5,
    min: 1,
    max: 1000,
    label: 'Order creation per minute',
  },
  {
    key: 'rateLimits.unlockPerMinute',
    section: SECTIONS.RATE_LIMITS,
    type: 'integer',
    default: 30,
    min: 1,
    max: 1000,
    label: 'Chapter unlocks per minute',
  },
  {
    key: 'rateLimits.couponValidatePerMinute',
    section: SECTIONS.RATE_LIMITS,
    type: 'integer',
    default: 10,
    min: 1,
    max: 1000,
    label: 'Coupon checks per minute',
  },
  {
    key: 'rateLimits.refundRequestPerDay',
    section: SECTIONS.RATE_LIMITS,
    type: 'integer',
    default: 3,
    min: 1,
    max: 100,
    label: 'Refund requests per day',
  },

  // ----------------------------------------------------------------- grants
  {
    key: 'grants.defaultExpiryDays',
    section: SECTIONS.GRANTS,
    type: 'integer',
    default: 0,
    min: 0,
    max: 3650,
    label: 'Default grant expiry',
    unit: 'days',
  },
  {
    key: 'grants.defaultChannels',
    section: SECTIONS.GRANTS,
    type: 'multiselect',
    default: ['in_app'],
    options: [
      { value: 'in_app', label: 'In-app' },
      { value: 'email', label: 'Email' },
    ],
    label: 'Default notification channels',
  },
  {
    key: 'grants.requireDryRun',
    section: SECTIONS.GRANTS,
    type: 'boolean',
    default: true,
    label: 'Require a dry run before executing',
  },
  {
    key: 'grants.approvalThresholdCredits',
    section: SECTIONS.GRANTS,
    type: 'integer',
    default: 100000,
    min: 0,
    max: 1000000000,
    label: 'Second approver required above',
    unit: 'total credits',
  },
  {
    key: 'grants.maxCreditsPerCampaign',
    section: SECTIONS.GRANTS,
    type: 'integer',
    default: 10000000,
    min: 0,
    max: 1000000000,
    label: 'Maximum credits per campaign',
  },
  {
    key: 'grants.reversalWindowDays',
    section: SECTIONS.GRANTS,
    type: 'integer',
    default: 30,
    min: 0,
    max: 365,
    label: 'Campaign reversal window',
    unit: 'days',
  },
];

module.exports = { settings, SECTIONS };
