// Platform settings — everything that was previously a hardcoded constant.
//
// Adding a new admin-controllable value is one entry in this file. The
// validator, coercion, admin form metadata, public projection, settings search
// index and audit diff are all derived from the declaration.

const SECTIONS = {
  RANKING: 'platform.ranking',
  DISCOVERY: 'platform.discovery',
  LIMITS: 'platform.limits',
  READER: 'platform.reader',
  NOTIFICATIONS: 'platform.notifications',
  VIEWS: 'platform.views',
  AUTH: 'platform.auth',
  COMMUNITY: 'platform.community',
};

const settings = [
  // ---------------------------------------------------------------- ranking
  {
    key: 'ranking.trendingWindowDays',
    section: SECTIONS.RANKING,
    type: 'integer',
    default: 7,
    min: 1,
    max: 90,
    label: 'Trending window',
    unit: 'days',
    help: 'How much history the trending score considers. Requires the trending reset job.',
    public: true,
  },
  {
    key: 'ranking.weights',
    section: SECTIONS.RANKING,
    type: 'json',
    default: { views: 1, recentViews: 3, rating: 2, engagement: 1.5, revenue: 0, ageDecay: 0.5 },
    label: 'Ranking score weights',
    help: 'Relative weight of each signal in the ranking score. Set revenue above 0 to promote what sells.',
    requiresConfirmation: true,
    impact: 'previewRankings',
  },
  {
    key: 'ranking.bayesianPriorVotes',
    section: SECTIONS.RANKING,
    type: 'integer',
    default: 20,
    min: 0,
    max: 1000,
    label: 'Rating prior strength',
    unit: 'votes',
    help: 'Pulls low-vote novels toward the site average, so one 5-star review cannot top the chart. 0 disables.',
  },
  {
    key: 'ranking.minVotesForRatingRank',
    section: SECTIONS.RANKING,
    type: 'integer',
    default: 5,
    min: 0,
    max: 1000,
    label: 'Minimum votes for rating rank',
    help: 'Novels below this are excluded from the top-rated ranking entirely.',
  },
  {
    key: 'ranking.ageDecayHalfLifeDays',
    section: SECTIONS.RANKING,
    type: 'integer',
    default: 30,
    min: 1,
    max: 365,
    label: 'Age decay half-life',
    unit: 'days',
    help: 'How quickly older novels fade from ranked lists.',
  },
  {
    key: 'ranking.trendingResetCron',
    section: SECTIONS.RANKING,
    type: 'cron',
    default: '0 4 * * 1',
    label: 'Trending reset schedule',
    help: 'When the rolling view counter resets. Without this job, trending is identical to all-time popular.',
  },

  // -------------------------------------------------------------- discovery
  {
    key: 'discovery.featuredLimit',
    section: SECTIONS.DISCOVERY,
    type: 'integer',
    default: 10,
    min: 1,
    max: 50,
    label: 'Featured novels shown',
    public: true,
  },
  {
    key: 'discovery.rankingsDefaultLimit',
    section: SECTIONS.DISCOVERY,
    type: 'integer',
    default: 10,
    min: 1,
    max: 100,
    label: 'Default ranking list length',
    public: true,
  },
  {
    key: 'discovery.homeSectionOrder',
    section: SECTIONS.DISCOVERY,
    type: 'multiselect',
    default: ['featured', 'trending', 'newArrivals', 'popular', 'completed', 'topRated'],
    options: [
      { value: 'featured', label: 'Featured' },
      { value: 'trending', label: 'Trending' },
      { value: 'newArrivals', label: 'New arrivals' },
      { value: 'popular', label: 'Popular' },
      { value: 'completed', label: 'Completed' },
      { value: 'topRated', label: 'Top rated' },
    ],
    label: 'Homepage section order',
    help: 'Drag to reorder. Visibility is controlled separately in site settings.',
    public: true,
  },
  {
    key: 'discovery.homeSectionItemCount',
    section: SECTIONS.DISCOVERY,
    type: 'integer',
    default: 12,
    min: 4,
    max: 40,
    label: 'Items per homepage section',
    public: true,
  },
  {
    key: 'discovery.carouselAutoFillThreshold',
    section: SECTIONS.DISCOVERY,
    type: 'integer',
    default: 4,
    min: 0,
    max: 20,
    label: 'Carousel auto-fill threshold',
    help: 'In hybrid mode, auto-generated slides are added when custom slides fall below this count.',
  },
  {
    key: 'discovery.carouselTargetSlides',
    section: SECTIONS.DISCOVERY,
    type: 'integer',
    default: 5,
    min: 1,
    max: 20,
    label: 'Carousel target slide count',
    public: true,
  },

  // ----------------------------------------------------------------- limits
  {
    key: 'limits.novelTitleMax',
    section: SECTIONS.LIMITS,
    type: 'integer',
    default: 200,
    min: 10,
    max: 500,
    label: 'Novel title length',
    unit: 'characters',
  },
  {
    key: 'limits.novelSynopsisMax',
    section: SECTIONS.LIMITS,
    type: 'integer',
    default: 5000,
    min: 100,
    max: 50000,
    label: 'Synopsis length',
    unit: 'characters',
  },
  {
    key: 'limits.chapterTitleMax',
    section: SECTIONS.LIMITS,
    type: 'integer',
    default: 300,
    min: 10,
    max: 1000,
    label: 'Chapter title length',
    unit: 'characters',
  },
  {
    key: 'limits.commentMax',
    section: SECTIONS.LIMITS,
    type: 'integer',
    default: 2000,
    min: 50,
    max: 20000,
    label: 'Comment length',
    unit: 'characters',
    public: true,
  },
  {
    key: 'limits.reviewMax',
    section: SECTIONS.LIMITS,
    type: 'integer',
    default: 2000,
    min: 50,
    max: 20000,
    label: 'Review length',
    unit: 'characters',
    public: true,
  },
  {
    key: 'limits.imageUploadMaxBytes',
    section: SECTIONS.LIMITS,
    type: 'integer',
    default: 5 * 1024 * 1024,
    min: 100 * 1024,
    max: 50 * 1024 * 1024,
    label: 'Image upload limit',
    unit: 'bytes',
  },
  {
    key: 'limits.docUploadMaxBytes',
    section: SECTIONS.LIMITS,
    type: 'integer',
    default: 20 * 1024 * 1024,
    min: 1024 * 1024,
    max: 200 * 1024 * 1024,
    label: 'Document upload limit',
    unit: 'bytes',
  },
  {
    key: 'limits.ratingScaleMax',
    section: SECTIONS.LIMITS,
    type: 'enum',
    default: '5',
    options: [
      { value: '5', label: '1 to 5 stars' },
      { value: '10', label: '1 to 10' },
    ],
    label: 'Rating scale',
    help: 'Changing this does not rescale existing ratings.',
    requiresConfirmation: true,
    public: true,
  },

  // ----------------------------------------------------------------- reader
  {
    key: 'reader.defaultTheme',
    section: SECTIONS.READER,
    type: 'enum',
    default: 'dark',
    options: [
      { value: 'dark', label: 'Dark' },
      { value: 'black', label: 'Black' },
      { value: 'sepia', label: 'Sepia' },
      { value: 'light', label: 'Light' },
    ],
    label: 'Default reader theme',
    public: true,
  },
  {
    key: 'reader.enabledThemes',
    section: SECTIONS.READER,
    type: 'multiselect',
    default: ['dark', 'black', 'sepia', 'light'],
    options: [
      { value: 'dark', label: 'Dark' },
      { value: 'black', label: 'Black' },
      { value: 'sepia', label: 'Sepia' },
      { value: 'light', label: 'Light' },
    ],
    label: 'Themes offered to readers',
    public: true,
  },
  {
    key: 'reader.defaultFontSize',
    section: SECTIONS.READER,
    type: 'integer',
    default: 19,
    min: 10,
    max: 48,
    label: 'Default font size',
    unit: 'px',
    public: true,
  },
  {
    key: 'reader.fontSizeMin',
    section: SECTIONS.READER,
    type: 'integer',
    default: 14,
    min: 8,
    max: 40,
    label: 'Minimum font size',
    unit: 'px',
    public: true,
  },
  {
    key: 'reader.fontSizeMax',
    section: SECTIONS.READER,
    type: 'integer',
    default: 32,
    min: 12,
    max: 80,
    label: 'Maximum font size',
    unit: 'px',
    public: true,
  },
  {
    key: 'reader.defaultLineHeight',
    section: SECTIONS.READER,
    type: 'number',
    default: 1.8,
    min: 1,
    max: 3,
    label: 'Default line height',
    public: true,
  },
  {
    key: 'reader.prefetchNextChapter',
    section: SECTIONS.READER,
    type: 'boolean',
    default: false,
    label: 'Prefetch the next chapter',
    help: 'Locked chapters are never prefetched regardless of this setting.',
    public: true,
  },

  // ---------------------------------------------------------- notifications
  {
    key: 'notifications.historyLimit',
    section: SECTIONS.NOTIFICATIONS,
    type: 'integer',
    default: 50,
    min: 10,
    max: 500,
    label: 'Notifications shown in the list',
    public: true,
  },
  {
    key: 'notifications.batchSize',
    section: SECTIONS.NOTIFICATIONS,
    type: 'integer',
    default: 250,
    min: 10,
    max: 2000,
    label: 'Campaign batch size',
    help: 'Recipients processed per batch. Lower this if your mail provider throttles.',
  },
  {
    key: 'notifications.maxMentionsPerComment',
    section: SECTIONS.NOTIFICATIONS,
    type: 'integer',
    default: 10,
    min: 0,
    max: 50,
    label: 'Mentions parsed per comment',
  },
  {
    key: 'notifications.retentionDays',
    section: SECTIONS.NOTIFICATIONS,
    type: 'integer',
    default: 0,
    min: 0,
    max: 3650,
    label: 'Notification retention',
    unit: 'days',
    help: '0 keeps them forever.',
  },
  {
    key: 'notifications.maxEmailsPerUserPerDay',
    section: SECTIONS.NOTIFICATIONS,
    type: 'integer',
    default: 10,
    min: 0,
    max: 200,
    label: 'Email cap per user per day',
    help: '0 removes the cap.',
  },
  {
    key: 'notifications.emailConcurrency',
    section: SECTIONS.NOTIFICATIONS,
    type: 'integer',
    default: 5,
    min: 1,
    max: 100,
    label: 'Concurrent email sends',
    help: 'Most SMTP providers throttle above 10 concurrent connections.',
  },
  {
    key: 'notifications.quietHours',
    section: SECTIONS.NOTIFICATIONS,
    type: 'json',
    default: { enabled: false, startHour: 22, endHour: 7, timezone: 'UTC' },
    label: 'Quiet hours',
    help: 'Email is deferred during this window. In-app notifications are unaffected.',
  },

  // ------------------------------------------------------------------ views
  {
    key: 'views.dedupWindowSeconds',
    section: SECTIONS.VIEWS,
    type: 'integer',
    default: 30 * 60,
    min: 60,
    max: 24 * 60 * 60,
    label: 'View dedup window',
    unit: 'seconds',
  },
  {
    key: 'views.countAnonymous',
    section: SECTIONS.VIEWS,
    type: 'boolean',
    default: true,
    label: 'Count logged-out views',
  },
  {
    key: 'views.filterBots',
    section: SECTIONS.VIEWS,
    type: 'boolean',
    default: true,
    label: 'Exclude known crawlers',
    help: 'Matches the user agent against a bot list before counting a view.',
  },
  {
    key: 'views.minDwellSeconds',
    section: SECTIONS.VIEWS,
    type: 'integer',
    default: 0,
    min: 0,
    max: 600,
    label: 'Minimum dwell before a view counts',
    unit: 'seconds',
    help: '0 counts the page load. Higher values need a client-side ping.',
  },
  {
    key: 'views.showCountsPublicly',
    section: SECTIONS.VIEWS,
    type: 'boolean',
    default: true,
    label: 'Show view counts to readers',
    public: true,
  },

  // ------------------------------------------------------------------- auth
  {
    key: 'auth.usernameMin',
    section: SECTIONS.AUTH,
    type: 'integer',
    default: 3,
    min: 1,
    max: 30,
    label: 'Username minimum length',
    public: true,
  },
  {
    key: 'auth.usernameMax',
    section: SECTIONS.AUTH,
    type: 'integer',
    default: 30,
    min: 5,
    max: 100,
    label: 'Username maximum length',
    public: true,
  },
  {
    key: 'auth.passwordMinLength',
    section: SECTIONS.AUTH,
    type: 'integer',
    default: 6,
    min: 6,
    max: 128,
    label: 'Password minimum length',
    public: true,
  },
  {
    key: 'auth.passwordRequireMixedCase',
    section: SECTIONS.AUTH,
    type: 'boolean',
    default: false,
    label: 'Require upper and lower case',
    public: true,
  },
  {
    key: 'auth.passwordRequireNumber',
    section: SECTIONS.AUTH,
    type: 'boolean',
    default: false,
    label: 'Require a number',
    public: true,
  },
  {
    key: 'auth.otpMaxAttempts',
    section: SECTIONS.AUTH,
    type: 'integer',
    default: 5,
    min: 1,
    max: 20,
    label: 'Verification code attempts',
  },
  {
    key: 'auth.otpResendCooldownSeconds',
    section: SECTIONS.AUTH,
    type: 'integer',
    default: 60,
    min: 10,
    max: 3600,
    label: 'Code resend cooldown',
    unit: 'seconds',
  },
  {
    key: 'auth.loginMaxAttempts',
    section: SECTIONS.AUTH,
    type: 'integer',
    default: 10,
    min: 0,
    max: 100,
    label: 'Failed logins before lockout',
    help: '0 disables lockout.',
  },
  {
    key: 'auth.loginLockoutMinutes',
    section: SECTIONS.AUTH,
    type: 'integer',
    default: 15,
    min: 1,
    max: 1440,
    label: 'Lockout duration',
    unit: 'minutes',
  },
  {
    key: 'auth.blockDisposableEmails',
    section: SECTIONS.AUTH,
    type: 'boolean',
    default: false,
    label: 'Block disposable email domains',
  },
  {
    key: 'auth.blockedEmailDomains',
    section: SECTIONS.AUTH,
    type: 'multiselect',
    default: [],
    maxItems: 500,
    label: 'Blocked email domains',
  },
  {
    key: 'auth.reservedUsernames',
    section: SECTIONS.AUTH,
    type: 'multiselect',
    default: ['admin', 'administrator', 'support', 'moderator', 'system', 'novelhub'],
    maxItems: 500,
    label: 'Reserved usernames',
  },
  {
    key: 'auth.requireAdmin2fa',
    section: SECTIONS.AUTH,
    type: 'boolean',
    default: false,
    label: 'Require 2FA for admin accounts',
    help: 'Strongly recommended once the portal can move money.',
  },

  // -------------------------------------------------------------- community
  {
    key: 'community.commentEditWindowMinutes',
    section: SECTIONS.COMMUNITY,
    type: 'integer',
    default: 15,
    min: 0,
    max: 1440,
    label: 'Comment edit window',
    unit: 'minutes',
    help: '0 disables editing.',
    public: true,
  },
  {
    key: 'community.maxReplyDepth',
    section: SECTIONS.COMMUNITY,
    type: 'integer',
    default: 3,
    min: 1,
    max: 10,
    label: 'Maximum reply depth',
    public: true,
  },
  {
    key: 'community.minAccountAgeHoursToComment',
    section: SECTIONS.COMMUNITY,
    type: 'integer',
    default: 0,
    min: 0,
    max: 720,
    label: 'Account age before commenting',
    unit: 'hours',
  },
  {
    key: 'community.commentsPerUserPerHour',
    section: SECTIONS.COMMUNITY,
    type: 'integer',
    default: 30,
    min: 0,
    max: 500,
    label: 'Comments per user per hour',
    help: '0 removes the limit.',
  },
  {
    key: 'community.bannedWords',
    section: SECTIONS.COMMUNITY,
    type: 'multiselect',
    default: [],
    maxItems: 2000,
    label: 'Banned words',
  },
  {
    key: 'community.bannedWordAction',
    section: SECTIONS.COMMUNITY,
    type: 'enum',
    default: 'flag',
    options: [
      { value: 'block', label: 'Reject the post' },
      { value: 'flag', label: 'Post but flag for review' },
      { value: 'hide', label: 'Post but hide from others' },
    ],
    label: 'When a banned word is found',
  },
  {
    key: 'community.blockLinksInComments',
    section: SECTIONS.COMMUNITY,
    type: 'boolean',
    default: false,
    label: 'Block links in comments',
  },
  {
    key: 'community.requireUnlockToReviewChapter',
    section: SECTIONS.COMMUNITY,
    type: 'boolean',
    default: false,
    label: 'Require unlocking a chapter before reviewing it',
    help: 'Stops paid chapters collecting reviews from people who never read them.',
  },
  {
    key: 'community.reportsToAutoHide',
    section: SECTIONS.COMMUNITY,
    type: 'integer',
    default: 5,
    min: 0,
    max: 100,
    label: 'Reports before auto-hiding',
    help: '0 disables auto-hide.',
  },
];

module.exports = { settings, SECTIONS };
