// Community ("spaces") settings — every admin-controllable value for the
// general-purpose community system.
//
// Namespace note: nine flat `community.*` keys already exist in platform.js and
// govern CHAPTER comments and reviews (community.bannedWords,
// community.reportsToAutoHide, …). This is a different subsystem, so it uses
// `spaces.*` — otherwise the admin portal's settings search would return two
// near-identically-named results for "banned words" controlling different
// things, which is a real usability failure at this surface size.
//
// `spaceOverridable: true` marks a key a space owner may override for their own
// space. Everything else is site-wide and admin-only. Admins can force any key
// on any space regardless of this flag.

const SECTIONS = {
  CORE: 'spaces.core',
  CREATION: 'spaces.creation',
  POSTING: 'spaces.posting',
  MEDIA: 'spaces.media',
  VOTING: 'spaces.voting',
  RANKING: 'spaces.ranking',
  MODERATION: 'spaces.moderation',
  FEED: 'spaces.feed',
  KARMA: 'spaces.karma',
  LINKS: 'spaces.links',
  ANALYTICS: 'spaces.analytics',
  SAFETY: 'spaces.safety',
  PRIVACY: 'spaces.privacy',
  SCALE: 'spaces.scale',
};

// Shipped topic taxonomy. Deliberately generic — a space is about anything.
const DEFAULT_TOPICS = [
  { key: 'general', label: 'General', order: 1 },
  { key: 'books', label: 'Books & Writing', order: 2 },
  { key: 'gaming', label: 'Gaming', order: 3 },
  { key: 'technology', label: 'Technology', order: 4 },
  { key: 'art', label: 'Art & Design', order: 5 },
  { key: 'music', label: 'Music', order: 6 },
  { key: 'film', label: 'Film & TV', order: 7 },
  { key: 'science', label: 'Science', order: 8 },
  { key: 'food', label: 'Food & Cooking', order: 9 },
  { key: 'sports', label: 'Sports', order: 10 },
  { key: 'lifestyle', label: 'Lifestyle', order: 11 },
  { key: 'help', label: 'Help & Support', order: 12 },
  { key: 'meta', label: 'Site Meta', order: 13 },
];

// Report reasons drive the report modal, the moderation queue grouping and the
// severity sort. Admin-editable without a deploy.
const DEFAULT_REPORT_REASONS = [
  { key: 'spam', label: 'Spam or advertising', appliesTo: 'all', severity: 2 },
  { key: 'harassment', label: 'Harassment or bullying', appliesTo: 'all', severity: 4 },
  { key: 'hate', label: 'Hate speech', appliesTo: 'all', severity: 5 },
  { key: 'violence', label: 'Violence or threats', appliesTo: 'all', severity: 5 },
  { key: 'sexual_content', label: 'Unmarked sexual content', appliesTo: 'all', severity: 4 },
  // Severity 5 hides on the FIRST report and escalates to the restricted
  // safety queue rather than ordinary moderation. For these the delay is the
  // harm, and being wrong costs an hour of one person's visibility.
  { key: 'minor_safety', label: 'Content involving a minor', appliesTo: 'all', severity: 5 },
  { key: 'self_harm', label: 'Self-harm or suicide', appliesTo: 'all', severity: 5 },
  { key: 'misinformation', label: 'Misinformation', appliesTo: 'all', severity: 2 },
  { key: 'personal_info', label: 'Sharing personal information', appliesTo: 'all', severity: 4 },
  { key: 'copyright', label: 'Copyright or IP violation', appliesTo: 'all', severity: 3 },
  { key: 'off_topic', label: 'Off topic for this space', appliesTo: 'post', severity: 1 },
  { key: 'rule_violation', label: 'Breaks a space rule', appliesTo: 'all', severity: 2 },
  { key: 'impersonation', label: 'Impersonation', appliesTo: 'all', severity: 3 },
  { key: 'other', label: 'Something else', appliesTo: 'all', severity: 1 },
];

const POST_TYPE_OPTIONS = [
  { value: 'text', label: 'Text post' },
  { value: 'image', label: 'Image / gallery' },
  { value: 'link', label: 'Link' },
  { value: 'poll', label: 'Poll' },
];

const SORT_OPTIONS = [
  { value: 'hot', label: 'Hot' },
  { value: 'new', label: 'New' },
  { value: 'top', label: 'Top' },
  { value: 'rising', label: 'Rising' },
  { value: 'controversial', label: 'Controversial' },
];

const COMMENT_SORT_OPTIONS = [
  { value: 'best', label: 'Best (confidence)' },
  { value: 'top', label: 'Top' },
  { value: 'new', label: 'New' },
  { value: 'old', label: 'Old' },
  { value: 'controversial', label: 'Controversial' },
];

const settings = [
  // ------------------------------------------------------------------- core
  {
    key: 'spaces.enabled',
    section: SECTIONS.CORE,
    type: 'boolean',
    default: false,
    label: 'Community enabled',
    help: 'Master switch. When off, every community route 404s and the navigation entry is hidden. Ships off so the feature can land in production before it is launched.',
    public: true,
    requiresConfirmation: true,
  },
  {
    key: 'spaces.publicBrowsing',
    section: SECTIONS.CORE,
    type: 'boolean',
    default: true,
    label: 'Signed-out visitors can browse',
    help: 'Off requires an account to read anything in the community.',
    public: true,
  },
  {
    key: 'spaces.entryPoint',
    section: SECTIONS.CORE,
    type: 'enum',
    default: 'nav',
    options: [
      { value: 'nav', label: 'Main navigation' },
      { value: 'footer', label: 'Footer link only' },
      { value: 'hidden', label: 'No link (direct URL only)' },
    ],
    label: 'Where the community is linked from',
    public: true,
  },
  {
    key: 'spaces.defaultLandingFeed',
    section: SECTIONS.CORE,
    type: 'enum',
    default: 'popular',
    options: [
      { value: 'home', label: 'Home (spaces you joined)' },
      { value: 'popular', label: 'Popular' },
      { value: 'all', label: 'All' },
    ],
    label: 'Default feed on arrival',
    public: true,
  },
  {
    key: 'spaces.core.topics',
    section: SECTIONS.CORE,
    type: 'json',
    default: DEFAULT_TOPICS,
    arrayOf: true,
    itemShape: ['key', 'label'],
    label: 'Topic taxonomy',
    help: 'The categories the space directory is browsed by. Generic by design — a space can be about anything.',
    public: true,
  },
  {
    key: 'spaces.core.searchEnabled',
    section: SECTIONS.CORE,
    type: 'boolean',
    default: true,
    label: 'Community search enabled',
    help: 'Per-subsystem kill switch. Search is the most expensive query on the site; this turns it off without turning off the community.',
    public: true,
  },
  {
    key: 'spaces.core.notificationsEnabled',
    section: SECTIONS.CORE,
    type: 'boolean',
    default: true,
    label: 'Community notifications enabled',
    help: 'Per-subsystem kill switch, separate from the site-wide notification settings.',
  },
  {
    key: 'spaces.core.terminology',
    section: SECTIONS.CORE,
    type: 'string',
    default: 'space',
    maxLength: 20,
    label: 'What a community is called',
    help: 'Singular noun used throughout the UI, e.g. "space", "circle", "hub". The URL prefix does not change.',
    public: true,
  },

  // --------------------------------------------------------------- creation
  {
    key: 'spaces.creation.mode',
    section: SECTIONS.CREATION,
    type: 'enum',
    default: 'karma_gated',
    options: [
      { value: 'open', label: 'Anyone signed in' },
      { value: 'karma_gated', label: 'Above a karma and age threshold' },
      { value: 'approval', label: 'Anyone may request, admin approves' },
      { value: 'admin_only', label: 'Admins only' },
    ],
    label: 'Who can create a space',
    help: 'Switchable at any time. A per-user override on the user record always wins over this.',
    public: true,
    requiresConfirmation: true,
  },
  {
    key: 'spaces.creation.minKarma',
    section: SECTIONS.CREATION,
    type: 'integer',
    default: 50,
    min: 0,
    max: 100000,
    label: 'Minimum karma to create',
    dependsOn: { key: 'spaces.creation.mode', value: 'karma_gated' },
  },
  {
    key: 'spaces.creation.minAccountAgeHours',
    section: SECTIONS.CREATION,
    type: 'integer',
    default: 72,
    min: 0,
    max: 8760,
    label: 'Minimum account age to create',
    unit: 'hours',
  },
  {
    key: 'spaces.creation.requireVerifiedEmail',
    section: SECTIONS.CREATION,
    type: 'boolean',
    default: true,
    label: 'Require a verified email to create',
  },
  {
    key: 'spaces.creation.maxPerUser',
    section: SECTIONS.CREATION,
    type: 'integer',
    default: 3,
    min: 0,
    max: 500,
    label: 'Spaces one user may own',
    help: '0 removes the cap.',
  },
  {
    key: 'spaces.creation.maxTotalSpaces',
    section: SECTIONS.CREATION,
    type: 'integer',
    default: 0,
    min: 0,
    max: 1000000,
    label: 'Site-wide space cap',
    help: '0 = unlimited. A hard brake if creation is abused.',
  },
  {
    key: 'spaces.creation.cooldownHours',
    section: SECTIONS.CREATION,
    type: 'integer',
    default: 24,
    min: 0,
    max: 8760,
    label: 'Cooldown between creations',
    unit: 'hours',
  },
  {
    key: 'spaces.creation.autoApproveAboveKarma',
    section: SECTIONS.CREATION,
    type: 'integer',
    default: 0,
    min: 0,
    max: 100000,
    label: 'Skip the approval queue above this karma',
    help: '0 means nobody skips the queue.',
    dependsOn: { key: 'spaces.creation.mode', value: 'approval' },
  },
  {
    key: 'spaces.creation.pendingExpiryDays',
    section: SECTIONS.CREATION,
    type: 'integer',
    default: 14,
    min: 1,
    max: 365,
    label: 'Unreviewed requests expire after',
    unit: 'days',
    help: 'Auto-rejects stale requests so an unattended queue degrades gracefully instead of leaving people waiting indefinitely.',
  },
  {
    key: 'spaces.creation.slugMinLength',
    section: SECTIONS.CREATION,
    type: 'integer',
    default: 3,
    min: 2,
    max: 20,
    label: 'Minimum slug length',
    public: true,
  },
  {
    key: 'spaces.creation.slugMaxLength',
    section: SECTIONS.CREATION,
    type: 'integer',
    default: 24,
    min: 5,
    max: 64,
    label: 'Maximum slug length',
    public: true,
  },
  {
    key: 'spaces.creation.reservedSlugs',
    section: SECTIONS.CREATION,
    type: 'multiselect',
    default: [
      'admin', 'api', 'mod', 'mods', 'help', 'about', 'store', 'settings',
      'login', 'signup', 'profile', 'library', 'search', 'new', 'create',
      'popular', 'all', 'home', 'support', 'staff', 'official', 'null', 'undefined',
    ],
    maxItems: 1000,
    label: 'Reserved slugs',
    help: 'Names nobody but an admin may register. Route names belong here.',
  },
  {
    key: 'spaces.creation.defaultVisibility',
    section: SECTIONS.CREATION,
    type: 'enum',
    default: 'public',
    options: [
      { value: 'public', label: 'Public' },
      { value: 'restricted', label: 'Restricted (anyone reads, approved members post)' },
      { value: 'private', label: 'Private (members only)' },
    ],
    label: 'Default visibility for a new space',
  },
  {
    key: 'spaces.creation.allowedVisibilities',
    section: SECTIONS.CREATION,
    type: 'multiselect',
    default: ['public'],
    options: [
      { value: 'public', label: 'Public' },
      { value: 'restricted', label: 'Restricted' },
      { value: 'private', label: 'Private' },
    ],
    label: 'Visibilities a creator may choose',
    help: 'Public-only keeps every feed and search query free of access filtering. Widen this once the permission surface has been load-tested.',
  },
  {
    key: 'spaces.creation.allowNsfw',
    section: SECTIONS.CREATION,
    type: 'boolean',
    default: false,
    label: 'Allow spaces marked NSFW',
    // READ BY THE SPA (CreateSpace.jsx). A setting the frontend reads must
    // be public, or the admin toggle is inert and nobody can tell.
    public: true,
  },
  {
    key: 'spaces.creation.requirePurpose',
    section: SECTIONS.CREATION,
    type: 'boolean',
    default: true,
    label: 'Require a stated purpose when requesting',
    help: 'Shown to the admin reviewing the request. Nothing filters low-effort requests better.',
    // READ BY THE SPA (CreateSpace.jsx). A setting the frontend reads must
    // be public, or the admin toggle is inert and nobody can tell.
    public: true,
  },

  // ---------------------------------------------------------------- posting
  {
    key: 'spaces.posting.allowedTypes',
    section: SECTIONS.POSTING,
    type: 'multiselect',
    default: ['text', 'image', 'link', 'poll'],
    options: POST_TYPE_OPTIONS,
    label: 'Post types allowed site-wide',
    help: 'A space can narrow this further, never widen it.',
    public: true,
    spaceOverridable: true,
  },
  {
    key: 'spaces.posting.minTitleLength',
    section: SECTIONS.POSTING,
    type: 'integer',
    default: 3,
    min: 1,
    max: 100,
    label: 'Minimum title length',
    public: true,
  },
  {
    key: 'spaces.posting.maxTitleLength',
    section: SECTIONS.POSTING,
    type: 'integer',
    default: 300,
    min: 10,
    max: 1000,
    label: 'Maximum title length',
    public: true,
  },
  {
    key: 'spaces.posting.maxBodyLength',
    section: SECTIONS.POSTING,
    type: 'integer',
    default: 40000,
    min: 100,
    max: 500000,
    label: 'Maximum post body length',
    unit: 'characters',
    public: true,
  },
  {
    key: 'spaces.posting.maxCommentLength',
    section: SECTIONS.POSTING,
    type: 'integer',
    default: 10000,
    min: 50,
    max: 100000,
    label: 'Maximum comment length',
    unit: 'characters',
    public: true,
  },
  {
    key: 'spaces.posting.editWindowMinutes',
    section: SECTIONS.POSTING,
    type: 'integer',
    default: 0,
    min: 0,
    max: 525600,
    label: 'Edit window',
    unit: 'minutes',
    help: '0 = editable forever. Every edit is timestamped regardless.',
    public: true,
  },
  {
    key: 'spaces.posting.titleLockMinutes',
    section: SECTIONS.POSTING,
    type: 'integer',
    default: 5,
    min: 0,
    max: 1440,
    label: 'Title becomes uneditable after',
    unit: 'minutes',
    help: 'Stops a popular post being rewritten into something else after it has collected votes.',
    public: true,
  },
  {
    key: 'spaces.posting.deleteWindowMinutes',
    section: SECTIONS.POSTING,
    type: 'integer',
    default: 0,
    min: 0,
    max: 525600,
    label: 'Author delete window',
    unit: 'minutes',
    help: '0 = always deletable.',
    public: true,
  },
  {
    key: 'spaces.posting.maxCommentDepth',
    section: SECTIONS.POSTING,
    type: 'integer',
    default: 10,
    min: 1,
    max: 50,
    label: 'Maximum reply depth',
    public: true,
  },
  {
    key: 'spaces.posting.initialCommentDepth',
    section: SECTIONS.POSTING,
    type: 'integer',
    default: 4,
    min: 1,
    max: 20,
    label: 'Depth loaded in the first payload',
    help: 'Deeper replies load on demand. Lower is faster on huge threads.',
    public: true,
  },
  {
    key: 'spaces.posting.postsPerHour',
    section: SECTIONS.POSTING,
    type: 'integer',
    default: 10,
    min: 0,
    max: 1000,
    label: 'Posts per user per hour',
    help: '0 removes the limit.',
  },
  {
    key: 'spaces.posting.commentsPerHour',
    section: SECTIONS.POSTING,
    type: 'integer',
    default: 60,
    min: 0,
    max: 5000,
    label: 'Comments per user per hour',
    help: '0 removes the limit.',
  },
  {
    key: 'spaces.posting.minAccountAgeHours',
    section: SECTIONS.POSTING,
    type: 'integer',
    default: 0,
    min: 0,
    max: 8760,
    label: 'Account age before posting',
    unit: 'hours',
    spaceOverridable: true,
  },
  {
    key: 'spaces.posting.minKarmaToPost',
    section: SECTIONS.POSTING,
    type: 'integer',
    default: 0,
    min: 0,
    max: 100000,
    label: 'Minimum karma to post',
    spaceOverridable: true,
  },
  {
    key: 'spaces.posting.minKarmaToComment',
    section: SECTIONS.POSTING,
    type: 'integer',
    default: 0,
    min: 0,
    max: 100000,
    label: 'Minimum karma to comment',
    spaceOverridable: true,
  },
  {
    key: 'spaces.posting.allowLinks',
    section: SECTIONS.POSTING,
    type: 'boolean',
    default: true,
    label: 'Allow links in posts and comments',
    spaceOverridable: true,
  },
  {
    key: 'spaces.posting.linkDomainAllowlist',
    section: SECTIONS.POSTING,
    type: 'multiselect',
    default: [],
    maxItems: 2000,
    label: 'Link domain allowlist',
    help: 'Empty allows every domain. Non-empty blocks everything else.',
  },
  {
    key: 'spaces.posting.linkDomainBlocklist',
    section: SECTIONS.POSTING,
    type: 'multiselect',
    default: [],
    maxItems: 5000,
    label: 'Link domain blocklist',
  },
  {
    key: 'spaces.posting.minKarmaToLink',
    section: SECTIONS.POSTING,
    type: 'integer',
    default: 0,
    min: 0,
    max: 100000,
    label: 'Minimum karma to post a link',
    help: 'The cheapest effective spam brake there is.',
  },
  {
    key: 'spaces.posting.fetchLinkPreviews',
    section: SECTIONS.POSTING,
    type: 'boolean',
    default: true,
    label: 'Fetch link previews',
    help: 'Server-side fetch of title, description and thumbnail for link posts.',
  },
  {
    key: 'spaces.posting.linkPreviewTimeoutMs',
    section: SECTIONS.POSTING,
    type: 'integer',
    default: 4000,
    min: 500,
    max: 30000,
    label: 'Link preview fetch timeout',
    unit: 'ms',
  },
  {
    key: 'spaces.posting.maxPollOptions',
    section: SECTIONS.POSTING,
    type: 'integer',
    default: 6,
    min: 2,
    max: 20,
    label: 'Maximum poll options',
    public: true,
  },
  {
    key: 'spaces.posting.maxPollDurationDays',
    section: SECTIONS.POSTING,
    type: 'integer',
    default: 7,
    min: 1,
    max: 90,
    label: 'Maximum poll duration',
    unit: 'days',
    public: true,
  },
  {
    key: 'spaces.posting.requireFlair',
    section: SECTIONS.POSTING,
    type: 'boolean',
    default: false,
    label: 'Require a flair on every post',
    spaceOverridable: true,
  },

  // ------------------------------------------------------------------ media
  {
    key: 'spaces.media.enabled',
    section: SECTIONS.MEDIA,
    type: 'boolean',
    default: true,
    label: 'Media uploads enabled',
    help: 'Off means no image posts, no inline images and no space banners.',
    public: true,
  },
  {
    key: 'spaces.media.maxImageBytes',
    section: SECTIONS.MEDIA,
    type: 'integer',
    default: 5242880,
    min: 65536,
    max: 104857600,
    label: 'Maximum size per image',
    unit: 'bytes',
    help: 'Enforced by a multer instance built per request, so a change here applies to the very next upload with no restart. 5242880 = 5 MB.',
    public: true,
  },
  {
    key: 'spaces.media.maxGifBytes',
    section: SECTIONS.MEDIA,
    type: 'integer',
    default: 10485760,
    min: 65536,
    max: 209715200,
    label: 'Maximum size per GIF',
    unit: 'bytes',
    help: 'GIFs get their own cap because they are routinely an order of magnitude larger. 10485760 = 10 MB.',
    public: true,
  },
  {
    key: 'spaces.media.maxImagesPerPost',
    section: SECTIONS.MEDIA,
    type: 'integer',
    default: 10,
    min: 1,
    max: 50,
    label: 'Maximum images per post',
    public: true,
  },
  {
    key: 'spaces.media.maxTotalPostBytes',
    section: SECTIONS.MEDIA,
    type: 'integer',
    default: 26214400,
    min: 65536,
    max: 524288000,
    label: 'Maximum total upload per post',
    unit: 'bytes',
    help: 'Sum across every file in one post. 26214400 = 25 MB.',
    public: true,
  },
  {
    key: 'spaces.media.uploadsPerHour',
    section: SECTIONS.MEDIA,
    type: 'number',
    default: 30,
    min: 0,
    max: 1000,
    label: 'Uploads per user per hour',
    help: 'Uploading is the most expensive request the server handles — multipart parsing, the whole file in memory, a hash lookup and an S3 put. 0 disables the limit.',
  },
  {
    key: 'spaces.media.maxDailyBytesPerUser',
    section: SECTIONS.MEDIA,
    type: 'integer',
    default: 104857600,
    min: 0,
    max: 10737418240,
    label: 'Maximum upload per user per day',
    unit: 'bytes',
    help: 'Storage-cost brake. 0 removes the limit. 104857600 = 100 MB.',
  },
  {
    key: 'spaces.media.allowedMimeTypes',
    section: SECTIONS.MEDIA,
    type: 'multiselect',
    default: ['image/jpeg', 'image/png', 'image/webp', 'image/gif'],
    options: [
      { value: 'image/jpeg', label: 'JPEG' },
      { value: 'image/png', label: 'PNG' },
      { value: 'image/webp', label: 'WebP' },
      { value: 'image/gif', label: 'GIF' },
      { value: 'image/avif', label: 'AVIF' },
    ],
    label: 'Allowed image types',
    help: 'SVG is deliberately not an option — it can carry script and is an XSS vector when served from your own domain.',
    public: true,
  },
  {
    key: 'spaces.media.maxImageWidth',
    section: SECTIONS.MEDIA,
    type: 'integer',
    default: 4096,
    min: 256,
    max: 20000,
    label: 'Maximum image width',
    unit: 'px',
    help: 'Rejects decompression bombs — a small file that expands to gigabytes in memory.',
  },
  {
    key: 'spaces.media.maxImageHeight',
    section: SECTIONS.MEDIA,
    type: 'integer',
    default: 4096,
    min: 256,
    max: 20000,
    label: 'Maximum image height',
    unit: 'px',
  },
  {
    key: 'spaces.media.stripExif',
    section: SECTIONS.MEDIA,
    type: 'boolean',
    default: true,
    label: 'Strip EXIF metadata',
    help: 'Removes GPS coordinates and device details from user photos. Leaving this off leaks people’s home addresses.',
  },
  {
    key: 'spaces.media.generateThumbnails',
    section: SECTIONS.MEDIA,
    type: 'boolean',
    default: true,
    label: 'Generate thumbnails',
  },
  {
    key: 'spaces.media.thumbnailWidth',
    section: SECTIONS.MEDIA,
    type: 'integer',
    default: 640,
    min: 120,
    max: 2048,
    label: 'Thumbnail width',
    unit: 'px',
  },
  {
    key: 'spaces.media.allowInlineEditorImages',
    section: SECTIONS.MEDIA,
    type: 'boolean',
    default: true,
    label: 'Allow images inside a text post body',
  },
  {
    key: 'spaces.media.iconMaxBytes',
    section: SECTIONS.MEDIA,
    type: 'integer',
    default: 1048576,
    min: 16384,
    max: 20971520,
    label: 'Maximum space icon size',
    unit: 'bytes',
  },
  {
    key: 'spaces.media.bannerMaxBytes',
    section: SECTIONS.MEDIA,
    type: 'integer',
    default: 5242880,
    min: 65536,
    max: 52428800,
    label: 'Maximum space banner size',
    unit: 'bytes',
  },
  {
    key: 'spaces.media.avatarMaxBytes',
    section: SECTIONS.MEDIA,
    type: 'integer',
    default: 2097152,
    min: 16384,
    max: 20971520,
    label: 'Maximum user avatar size',
    unit: 'bytes',
  },

  // ----------------------------------------------------------------- voting
  {
    key: 'spaces.voting.enabled',
    section: SECTIONS.VOTING,
    type: 'boolean',
    default: true,
    label: 'Voting enabled',
    public: true,
  },
  {
    key: 'spaces.voting.allowDownvotes',
    section: SECTIONS.VOTING,
    type: 'boolean',
    default: true,
    label: 'Allow downvotes',
    help: 'Off turns voting into likes only. Friendlier, but removes the community’s main tool for burying bad content.',
    public: true,
  },
  {
    key: 'spaces.voting.showScoreBeforeHours',
    section: SECTIONS.VOTING,
    type: 'integer',
    default: 0,
    min: 0,
    max: 168,
    label: 'Hide scores for the first',
    unit: 'hours',
    help: 'Reduces bandwagoning on new posts. 0 always shows the score.',
    public: true,
    spaceOverridable: true,
  },
  {
    key: 'spaces.voting.hideDownvoteCount',
    section: SECTIONS.VOTING,
    type: 'boolean',
    default: true,
    label: 'Show net score only',
    help: 'Hides the raw downvote count. Reduces pile-on dynamics.',
    public: true,
  },
  {
    key: 'spaces.voting.minAccountAgeHours',
    section: SECTIONS.VOTING,
    type: 'integer',
    default: 0,
    min: 0,
    max: 8760,
    label: 'Account age before voting',
    unit: 'hours',
  },
  {
    key: 'spaces.voting.minKarmaToDownvote',
    section: SECTIONS.VOTING,
    type: 'integer',
    default: 0,
    min: 0,
    max: 100000,
    label: 'Minimum karma to downvote',
  },
  {
    key: 'spaces.voting.perMinuteLimit',
    section: SECTIONS.VOTING,
    type: 'integer',
    default: 60,
    min: 0,
    max: 1000,
    label: 'Votes per user per minute',
    help: '0 removes the limit.',
  },
  {
    key: 'spaces.voting.allowVoteChange',
    section: SECTIONS.VOTING,
    type: 'boolean',
    default: true,
    label: 'Allow changing or removing a vote',
    public: true,
  },

  // ---------------------------------------------------------------- ranking
  {
    key: 'spaces.ranking.defaultSort',
    section: SECTIONS.RANKING,
    type: 'enum',
    default: 'hot',
    options: SORT_OPTIONS,
    label: 'Default post sort',
    public: true,
    spaceOverridable: true,
  },
  {
    key: 'spaces.ranking.defaultCommentSort',
    section: SECTIONS.RANKING,
    type: 'enum',
    default: 'best',
    options: COMMENT_SORT_OPTIONS,
    label: 'Default comment sort',
    public: true,
    spaceOverridable: true,
  },
  {
    key: 'spaces.ranking.hotGravitySeconds',
    section: SECTIONS.RANKING,
    type: 'integer',
    default: 45000,
    min: 3600,
    max: 604800,
    label: 'Hot ranking gravity',
    unit: 'seconds',
    help: 'How much one order of magnitude of score is worth in time. Lower churns the feed faster; higher lets good posts persist. 45000 is about 12.5 hours. The single most consequential dial in the community.',
    requiresConfirmation: true,
  },
  {
    key: 'spaces.ranking.confidenceZ',
    section: SECTIONS.RANKING,
    type: 'number',
    default: 1.281655,
    min: 0.5,
    max: 3,
    label: 'Confidence sort z-score',
    help: 'Wilson lower-bound parameter for the Best sort. 1.281655 is an 80% confidence interval. Higher is more conservative toward low-vote items.',
  },
  {
    key: 'spaces.ranking.risingWindowHours',
    section: SECTIONS.RANKING,
    type: 'integer',
    default: 6,
    min: 1,
    max: 72,
    label: 'Rising window',
    unit: 'hours',
  },
  {
    key: 'spaces.ranking.risingMinScore',
    section: SECTIONS.RANKING,
    type: 'integer',
    default: 5,
    min: 1,
    max: 1000,
    label: 'Minimum score to appear in Rising',
  },
  {
    key: 'spaces.ranking.pinnedSlots',
    section: SECTIONS.RANKING,
    type: 'integer',
    default: 3,
    min: 0,
    max: 10,
    label: 'Pinned posts per space',
    spaceOverridable: true,
  },
  {
    key: 'spaces.ranking.rescoreCron',
    section: SECTIONS.RANKING,
    type: 'cron',
    default: '0 */6 * * *',
    label: 'Hot score refresh schedule',
    help: 'Advances time decay on posts that are not being voted on. Without this job, a dead post keeps the score it had when its last vote landed.',
  },
  {
    key: 'spaces.ranking.rescoreMaxAgeHours',
    section: SECTIONS.RANKING,
    type: 'integer',
    default: 168,
    min: 24,
    max: 8760,
    label: 'Rescore posts newer than',
    unit: 'hours',
    help: 'Bounds the rescore job. Older posts are already far below the fold.',
  },

  // ------------------------------------------------------------- moderation
  {
    key: 'spaces.moderation.autoHideReports',
    section: SECTIONS.MODERATION,
    type: 'integer',
    default: 5,
    min: 0,
    max: 1000,
    label: 'Reports before auto-hiding',
    help: '0 disables auto-hide. Hidden content stays visible to mods and its author.',
  },
  {
    key: 'spaces.moderation.reportReasons',
    section: SECTIONS.MODERATION,
    type: 'json',
    default: DEFAULT_REPORT_REASONS,
    arrayOf: true,
    itemShape: ['key', 'label'],
    label: 'Report reasons',
    help: 'Drives the report dialog, the queue grouping and the severity sort.',
    public: true,
  },
  {
    key: 'spaces.moderation.bannedWords',
    section: SECTIONS.MODERATION,
    type: 'multiselect',
    default: [],
    maxItems: 2000,
    label: 'Banned words (community)',
    help: 'Separate from the chapter-comment list. A space can add its own on top of this.',
  },
  {
    key: 'spaces.moderation.bannedWordAction',
    section: SECTIONS.MODERATION,
    type: 'enum',
    default: 'flag',
    options: [
      { value: 'block', label: 'Reject the post' },
      { value: 'flag', label: 'Publish but flag for review' },
      { value: 'hide', label: 'Publish but hide from others' },
    ],
    label: 'When a banned word is found',
  },
  {
    key: 'spaces.moderation.newUserApprovalPosts',
    section: SECTIONS.MODERATION,
    type: 'integer',
    default: 0,
    min: 0,
    max: 100,
    label: 'Hold a new user’s first N posts for approval',
    help: '0 disables. The most effective spam control there is, at the cost of moderator time.',
    spaceOverridable: true,
  },
  {
    key: 'spaces.moderation.duplicateWindowHours',
    section: SECTIONS.MODERATION,
    type: 'integer',
    default: 24,
    min: 0,
    max: 720,
    label: 'Reject a duplicate link within',
    unit: 'hours',
    help: '0 allows duplicates.',
  },
  {
    key: 'spaces.moderation.maxModsPerSpace',
    section: SECTIONS.MODERATION,
    type: 'integer',
    default: 20,
    min: 1,
    max: 200,
    label: 'Maximum moderators per space',
  },
  {
    key: 'spaces.moderation.maxRulesPerSpace',
    section: SECTIONS.MODERATION,
    type: 'integer',
    default: 15,
    min: 1,
    max: 50,
    label: 'Maximum rules per space',
  },
  {
    key: 'spaces.moderation.publicModlogDefault',
    section: SECTIONS.MODERATION,
    type: 'boolean',
    default: false,
    label: 'Moderation logs public by default',
    help: 'A space can opt in either way. Public logs build trust and expose moderators to argument.',
    spaceOverridable: true,
  },
  {
    key: 'spaces.moderation.removalReasonRequired',
    section: SECTIONS.MODERATION,
    type: 'boolean',
    default: true,
    label: 'Require a reason on every removal',
  },
  {
    key: 'spaces.moderation.notifyOnRemoval',
    section: SECTIONS.MODERATION,
    type: 'boolean',
    default: true,
    label: 'Tell the author when their content is removed',
    help: 'Silent removal is the single biggest driver of "why did my post disappear" support load.',
  },
  {
    key: 'spaces.moderation.maxReportsPerUserPerDay',
    section: SECTIONS.MODERATION,
    type: 'integer',
    default: 20,
    min: 0,
    max: 500,
    label: 'Reports one user may file per day',
    help: 'Blunts report-brigading. 0 removes the limit.',
  },
  {
    key: 'spaces.moderation.shadowbanEnabled',
    section: SECTIONS.MODERATION,
    type: 'boolean',
    default: false,
    label: 'Enable shadowbanning',
    help: 'A shadowbanned user sees their own content normally; nobody else does. Effective against determined spammers, and indefensible if used on a real person by mistake.',
    requiresConfirmation: true,
  },
  {
    key: 'spaces.moderation.banAppealEnabled',
    section: SECTIONS.MODERATION,
    type: 'boolean',
    default: true,
    label: 'Allow banned users to appeal',
  },

  // ------------------------------------------------------------------- feed
  {
    key: 'spaces.feed.pageSize',
    section: SECTIONS.FEED,
    type: 'integer',
    default: 25,
    min: 5,
    max: 100,
    label: 'Posts per feed page',
    public: true,
  },
  {
    key: 'spaces.feed.maxPageSize',
    section: SECTIONS.FEED,
    type: 'integer',
    default: 100,
    min: 10,
    max: 500,
    label: 'Maximum requestable page size',
    help: 'Caps what a client can ask for. Without it, one request can pull the whole collection.',
  },
  {
    key: 'spaces.feed.homeMinSpaces',
    section: SECTIONS.FEED,
    type: 'integer',
    default: 3,
    min: 0,
    max: 50,
    label: 'Spaces joined before Home replaces Popular',
    help: 'A home feed built from one space is worse than Popular. Below this, show Popular instead.',
    public: true,
  },
  {
    key: 'spaces.feed.popularMinMembers',
    section: SECTIONS.FEED,
    type: 'integer',
    default: 10,
    min: 0,
    max: 100000,
    label: 'Members before a space reaches Popular',
  },
  {
    key: 'spaces.feed.showNsfwByDefault',
    section: SECTIONS.FEED,
    type: 'boolean',
    default: false,
    label: 'Show NSFW content by default',
    public: true,
  },
  {
    key: 'spaces.feed.infiniteScroll',
    section: SECTIONS.FEED,
    type: 'boolean',
    default: true,
    label: 'Infinite scroll',
    public: true,
  },
  {
    key: 'spaces.feed.defaultDensity',
    section: SECTIONS.FEED,
    type: 'enum',
    default: 'card',
    options: [
      { value: 'card', label: 'Card' },
      { value: 'compact', label: 'Compact' },
      { value: 'classic', label: 'Classic' },
    ],
    label: 'Default feed density',
    public: true,
  },
  {
    key: 'spaces.feed.cacheSeconds',
    section: SECTIONS.FEED,
    type: 'integer',
    default: 0,
    min: 0,
    max: 300,
    label: 'Feed cache duration',
    unit: 'seconds',
    help: '0 disables caching. Anonymous Popular and All feeds are the ones worth caching under load.',
  },

  // ------------------------------------------------------------------ karma
  {
    key: 'spaces.karma.enabled',
    section: SECTIONS.KARMA,
    type: 'boolean',
    default: true,
    label: 'Karma enabled',
    help: 'Off also disables every karma-based gate elsewhere in these settings.',
    public: true,
  },
  {
    key: 'spaces.karma.postUpvoteValue',
    section: SECTIONS.KARMA,
    type: 'number',
    default: 1,
    min: 0,
    max: 100,
    label: 'Karma per post upvote',
  },
  {
    key: 'spaces.karma.commentUpvoteValue',
    section: SECTIONS.KARMA,
    type: 'number',
    default: 1,
    min: 0,
    max: 100,
    label: 'Karma per comment upvote',
  },
  {
    key: 'spaces.karma.downvotePenalty',
    section: SECTIONS.KARMA,
    type: 'number',
    default: 1,
    min: 0,
    max: 100,
    label: 'Karma lost per downvote',
  },
  {
    key: 'spaces.karma.perPostCap',
    section: SECTIONS.KARMA,
    type: 'integer',
    default: 0,
    min: 0,
    max: 100000,
    label: 'Maximum karma from one post',
    help: '0 = uncapped. A cap stops one viral post from permanently outranking sustained contribution.',
  },
  {
    key: 'spaces.karma.showOnProfile',
    section: SECTIONS.KARMA,
    type: 'boolean',
    default: true,
    label: 'Show karma on profiles',
    public: true,
  },
  {
    key: 'spaces.karma.showOnPost',
    section: SECTIONS.KARMA,
    type: 'boolean',
    default: true,
    label: 'Show author karma on posts',
    public: true,
  },
  {
    key: 'spaces.karma.recomputeCron',
    section: SECTIONS.KARMA,
    type: 'cron',
    default: '30 3 * * *',
    label: 'Karma rebuild schedule',
    help: 'Recomputes karma from the vote ledger, correcting any drift.',
  },

  // ------------------------------------------------------------------ links
  {
    key: 'spaces.links.enabledTypes',
    section: SECTIONS.LINKS,
    type: 'multiselect',
    default: ['novel', 'chapter'],
    options: [
      { value: 'novel', label: 'Novel' },
      { value: 'chapter', label: 'Chapter' },
    ],
    label: 'Entity types a post or space may link to',
    help: 'The community is general-purpose; this is optional platform integration. An empty list removes linking entirely.',
    public: true,
  },
  {
    key: 'spaces.links.maxPerPost',
    section: SECTIONS.LINKS,
    type: 'integer',
    default: 3,
    min: 0,
    max: 20,
    label: 'Maximum linked entities per post',
    public: true,
  },
  {
    key: 'spaces.links.maxPerSpace',
    section: SECTIONS.LINKS,
    type: 'integer',
    default: 5,
    min: 0,
    max: 50,
    label: 'Maximum linked entities per space',
  },
  {
    key: 'spaces.links.showDiscussionTab',
    section: SECTIONS.LINKS,
    type: 'boolean',
    default: true,
    label: 'Show a Discussion tab on linked entities',
    help: 'Adds a community tab to novel and chapter pages listing posts that link to them.',
    public: true,
  },

  // -------------------------------------------------------------- analytics
  {
    key: 'spaces.analytics.rollupCron',
    section: SECTIONS.ANALYTICS,
    type: 'cron',
    default: '15 2 * * *',
    label: 'Community rollup schedule',
    help: 'Builds the daily stats the admin charts read. Charts never query raw collections.',
  },
  {
    key: 'spaces.analytics.retainRawDays',
    section: SECTIONS.ANALYTICS,
    type: 'integer',
    default: 90,
    min: 7,
    max: 3650,
    label: 'Retain raw event data for',
    unit: 'days',
    help: 'Rollups are kept indefinitely; the raw rows behind them are pruned after this.',
  },
  {
    key: 'spaces.analytics.trackPostViews',
    section: SECTIONS.ANALYTICS,
    type: 'boolean',
    default: true,
    label: 'Count post views',
    help: 'Reuses the existing deduplicated view tracking.',
  },

  // ----------------------------------------------------------------- safety
  {
    key: 'spaces.safety.jurisdictionMode',
    section: SECTIONS.SAFETY,
    type: 'enum',
    default: 'standard',
    options: [
      { value: 'standard', label: 'Standard' },
      { value: 'eu', label: 'EU — Digital Services Act duties' },
      { value: 'uk', label: 'UK — Online Safety Act duties' },
      { value: 'strict', label: 'Strict — every duty, everywhere' },
    ],
    label: 'Regulatory mode',
    help: 'Selects which legal duties are enforced, so one deployment can serve multiple regimes. EU adds public reporting and statement-of-reasons requirements; UK adds age assurance and access assessments.',
    requiresConfirmation: true,
  },
  {
    key: 'spaces.safety.minAgeYears',
    section: SECTIONS.SAFETY,
    type: 'integer',
    default: 13,
    min: 13,
    max: 21,
    label: 'Minimum age to use the community',
    help: 'Below 13 triggers COPPA in the US, which requires verifiable parental consent. 13 is the cheap answer.',
    public: true,
  },
  {
    key: 'spaces.safety.requireAdultVerificationForNsfw',
    section: SECTIONS.SAFETY,
    type: 'boolean',
    default: false,
    label: 'Require verified adult status for NSFW spaces',
    help: 'A self-declared checkbox is not effective age assurance under the UK Online Safety Act. Needs an age assurance provider configured.',
  },
  {
    key: 'spaces.safety.escalateToSafetyQueue',
    section: SECTIONS.SAFETY,
    type: 'boolean',
    default: true,
    label: 'Route child-safety reports to the restricted queue',
    help: 'Keeps them out of the ordinary moderation queue and away from community moderators. Turning this off is almost certainly a mistake.',
  },

  // ---------------------------------------------------------------- privacy
  {
    key: 'spaces.privacy.ipRetentionDays',
    section: SECTIONS.PRIVACY,
    type: 'integer',
    default: 90,
    min: 0,
    max: 3650,
    label: 'Retain IP addresses for',
    unit: 'days',
    help: 'IPs are stored for abuse detection. Unpurged logs are a liability with no upside. 0 disables IP storage entirely.',
  },
  {
    key: 'spaces.privacy.fingerprintRetentionDays',
    section: SECTIONS.PRIVACY,
    type: 'integer',
    default: 90,
    min: 0,
    max: 3650,
    label: 'Retain device fingerprints for',
    unit: 'days',
  },
  {
    key: 'spaces.privacy.deletionGraceDays',
    section: SECTIONS.PRIVACY,
    type: 'integer',
    default: 30,
    min: 0,
    max: 180,
    label: 'Account deletion grace period',
    unit: 'days',
    help: 'A reversible window before the cascade runs. Prevents the rage-quit-and-regret support ticket, which is otherwise a guaranteed recurring cost.',
  },
  {
    key: 'spaces.privacy.exportEnabled',
    section: SECTIONS.PRIVACY,
    type: 'boolean',
    default: true,
    label: 'Allow self-serve data export',
    help: 'GDPR-class portability right. Turning it off does not remove the obligation, only the automation.',
  },

  // ------------------------------------------------------------------ scale
  {
    key: 'spaces.scale.counterMode',
    section: SECTIONS.SCALE,
    type: 'enum',
    default: 'direct',
    options: [
      { value: 'direct', label: 'Direct — one write per change' },
      { value: 'batched', label: 'Batched — accumulate and flush' },
    ],
    label: 'Counter write mode',
    help: 'Switch to batched when a viral post causes write conflicts on a single document. Can be switched under load and switched back, without shipping code during an incident.',
  },
  {
    key: 'spaces.scale.counterFlushMs',
    section: SECTIONS.SCALE,
    type: 'integer',
    default: 1000,
    min: 100,
    max: 30000,
    label: 'Counter flush window',
    unit: 'ms',
    help: 'How long deltas accumulate in batched mode. A crash loses at most one window, which for a vote counter is acceptable.',
    dependsOn: { key: 'spaces.scale.counterMode', value: 'batched' },
  },
  {
    key: 'spaces.scale.maxJoinedSpaces',
    section: SECTIONS.SCALE,
    type: 'integer',
    default: 500,
    min: 10,
    max: 10000,
    label: 'Maximum spaces a user may join',
    help: 'Bounds the home feed query. High enough that nobody notices; low enough that the query stays an index scan.',
    public: true,
  },
  {
    key: 'spaces.scale.homeFeedMaxSpaces',
    section: SECTIONS.SCALE,
    type: 'integer',
    default: 100,
    min: 5,
    max: 1000,
    label: 'Spaces included in the home feed query',
    help: 'When a user has joined more than this, the feed uses their most-active subset.',
  },
  {
    key: 'spaces.scale.commentTreeMaxNodes',
    section: SECTIONS.SCALE,
    type: 'integer',
    default: 500,
    min: 20,
    max: 5000,
    label: 'Maximum comments in one payload',
    help: 'A 10,000-comment thread cannot ship as a single response. Deeper replies load on demand.',
    public: true,
  },
  {
    key: 'spaces.scale.slowQueryMs',
    section: SECTIONS.SCALE,
    type: 'integer',
    default: 100,
    min: 10,
    max: 10000,
    label: 'Slow query threshold',
    unit: 'ms',
    help: 'Queries above this are logged and surfaced in the admin portal.',
  },
  {
    key: 'spaces.scale.readPreference',
    section: SECTIONS.SCALE,
    type: 'enum',
    default: 'primary',
    options: [
      { value: 'primary', label: 'Primary only' },
      { value: 'secondaryPreferred', label: 'Secondary preferred for feeds' },
    ],
    label: 'Feed read preference',
    help: 'Switch to secondary once read replicas exist. Vote state and permission checks always read from the primary regardless.',
  },
  {
    key: 'spaces.scale.voteHotWindowDays',
    section: SECTIONS.SCALE,
    type: 'integer',
    default: 180,
    min: 30,
    max: 3650,
    label: 'Keep individual votes online for',
    unit: 'days',
    help: 'Older votes are aggregated into an archive. This is what keeps the vote collection roughly flat instead of growing forever — the one real scaling lever in the system.',
  },
  {
    key: 'spaces.scale.voteArchiveCron',
    section: SECTIONS.SCALE,
    type: 'cron',
    default: '0 4 * * 0',
    label: 'Vote archival schedule',
  },
];

module.exports = { settings, SECTIONS };
